# Generated by Django 3.2 on 2023-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='86177ab8-1725-436c-bd22-ac234b7049fb', max_length=50, verbose_name='Код подтверждения'),
        ),
    ]
