# Generated by Django 3.2 on 2023-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230218_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='3976c92c-7db1-4ff6-8c79-436858b8d1e6', max_length=50, verbose_name='Код подтверждения'),
        ),
    ]
